# Generated by Django 2.2.6 on 2019-11-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_tag_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
