# Generated by Django 2.2.6 on 2019-10-28 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('satisfaction', models.IntegerField(verbose_name=range(0, 5))),
                ('items', models.ManyToManyField(related_name='item_list', to='item.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits_owned_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
