# Generated by Django 2.2.6 on 2019-11-05 09:29

from django.db import migrations, models
import outfit.models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='image_link',
        ),
        migrations.AddField(
            model_name='outfit',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=outfit.models.user_directory_path),
        ),
    ]
