# Generated by Django 2.2.6 on 2019-11-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0002_outfit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='tempAvg',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='outfit',
            name='tempIcon',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='image_link',
            field=models.CharField(max_length=100),
        ),
    ]
