# Generated by Django 2.2.6 on 2019-11-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0003_auto_20191125_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='satisfaction',
            field=models.IntegerField(default=5, verbose_name=range(0, 6)),
        ),
    ]
