# Generated by Django 2.2.6 on 2019-12-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0005_auto_20191125_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='dateWithTime',
            field=models.CharField(default='', max_length=20),
        ),
    ]
