# Generated by Django 2.2.6 on 2019-12-05 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0006_auto_20191128_2241'),
        ('outfit', '0006_outfit_datewithtime'),
    ]

    operations = [
    ]
