# Generated by Django 2.2.6 on 2019-12-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0007_merge_20191205_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
