# Generated by Django 2.2.6 on 2019-12-05 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0007_merge_20191205_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='dateWithTime',
        ),
    ]
