# Generated by Django 2.2.6 on 2019-12-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0008_auto_20191207_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='tempAvg',
            field=models.IntegerField(default=100, null=True),
        ),
    ]
