# Generated by Django 2.2.6 on 2019-12-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0010_auto_20191207_1601'),
        ('outfit', '0008_remove_outfit_datewithtime'),
    ]

    operations = [
    ]
