# Generated by Django 2.2.6 on 2019-12-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0014_auto_20191214_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='image_link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='tempIcon',
            field=models.CharField(default='', max_length=255),
        ),
    ]
