

# Generated by Django 2.2.6 on 2019-11-16 05:55


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(related_name='tag_list', to='tag.Tag'),
        ),
    ]
